# 热力图贪吃蛇，那没有热力吃什么呢？

name: snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-snake.svg
            snake/github-snake-dark.svg?palette=github-dark
      - uses: casperdcl/push-dir@v1
        with:
          message: Snake
          branch: snake
          dir: snake
          history: false
