# 热力图贪吃蛇，那没有热力吃什么？

name: Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  snack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snack/github-snake.svg
            snack/github-snake-dark.svg?palette=github-dark
      - uses: casperdcl/push-dir@v1
        with:
          message: Snack
          branch: snack
          dir: snack
          history: true

# 没有热力就摁造 懂的都懂
#      - name: Push to GitHub
#        uses: EndBug/add-and-commit@v7.2.1
#        with:
#          branch: main
#          message: 'Generate Contribution Snake'
